sudo: required
language: ruby

services:
  - docker

before_install:
  - bundle install

script:
  - kitchen conv
  - kitchen conv | grep changed=0
  - kitchen verify

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
