sudo: required
language: ruby

env:
  - ANSIBLE_VERSION=2.2.3.0
  - ANSIBLE_VERSION=2.3.3.0
  - ANSIBLE_VERSION=2.4.3.0
  - ANSIBLE_VERSION=2.5.0.0
services:
  - docker

before_install:
  - bundle install

script:
  - kitchen conv bind
  - kitchen conv bind | grep changed=0
  - kitchen verify bind
  - kitchen conv bind-zones-subset
  - kitchen conv bind-zones-subset | grep changed=0
  - kitchen verify bind-zones-subset

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
